"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useState } from "react";

export default function Onboarding(){
  const {step}=useParams<{step:string}>();const router=useRouter();const current=Number(step.replace("step-",""))||1;const [testing,setTesting]=useState(false);const [connected,setConnected]=useState(false);
  function next(){if(current===1){setTesting(true);setTimeout(()=>{setTesting(false);setConnected(true);setTimeout(()=>router.push("/onboarding/step-2"),450)},900)}else if(current===2)router.push("/onboarding/step-3");else router.push("/dashboard")}
  return <main className="onboarding"><nav><Link href="/" className="wordmark"><span>GH</span> Ghost Hand Intelligence</Link><button onClick={()=>router.push("/dashboard")}>Skip to demo →</button></nav><section className="onboarding-shell"><div className="onboarding-progress">{[1,2,3].map(n=><i className={n<=current?"active":""} key={n}/>)}</div><div className="eyebrow"><i/>GUIDED SETUP · STEP {current} OF 3</div>
    {current===1&&<><h1>Connect your DMS.</h1><p>Choose the system that anchors your dealership. This prototype simulates a secure, read-only connection.</p><label className="field">DMS PROVIDER<select><option>CROSS3</option><option>CDK Global</option><option>Reynolds & Reynolds</option></select></label><label className="field">DEALER ID<input defaultValue="PC-10294"/></label><label className="field">ACCESS KEY<input type="password" defaultValue="ghost-hand-demo"/></label>{connected&&<div className="setup-success">✓ Connection verified · 12 exports found</div>}</>}
    {current===2&&<><h1>Select your data sources.</h1><p>Ghost Hand found 12 compatible exports. Recommended sources are already selected.</p><div className="onboarding-sources">{["Vehicle sales","Test drives","Inventory","Service appointments","Repair orders","Warranty claims","Parts orders","Backorders"].map((s,i)=><label key={s}><input type="checkbox" defaultChecked={i!==2}/><span>{s}</span>{i<5&&<b>RECOMMENDED</b>}</label>)}</div><div className="setup-summary">12 exports · approximately 14,802 records per day</div></>}
    {current===3&&<><h1>Set your signal thresholds.</h1><p>Start with recommended operating baselines. Every threshold can be tuned later.</p><div className="thresholds">{[["Revenue impact","$25,000",55],["Forecast deviation","20%",42],["Inventory exposure","$15,000",35]].map(t=><label key={t[0] as string}><span>{t[0]}<b>{t[1]}</b></span><input type="range" defaultValue={t[2] as number}/></label>)}</div><div className="notify-choices"><label><input type="checkbox" defaultChecked/>Email critical alerts</label><label><input type="checkbox" defaultChecked/>Include in Monday brief</label><label><input type="checkbox"/>Send to Slack</label></div></>}
    <div className="onboarding-actions">{current>1?<Link href={`/onboarding/step-${current-1}`}>← Back</Link>:<span/>}<button onClick={next} disabled={testing} className="proto-btn lime">{testing?"Testing connection…":current===3?"Open my dashboard →":"Continue →"}</button></div>
  </section><aside><span>WHAT HAPPENS NEXT</span><b>{current===1?"We map your exports.":current===2?"We establish baselines.":"We surface what matters."}</b><p>{current===1?"Ghost Hand reads the structure without changing the source system.":current===2?"Normal patterns become the reference point for anomaly detection.":"Signals are ranked by material impact and routed to the right role."}</p></aside></main>
}
