"use client";

import { useEffect, useState } from "react";
import { PrototypeShell } from "@/components/PrototypeShell";
import { Drawer, Modal, Toast, downloadText } from "@/components/PrototypeUI";

const templates=[["Weekly Executive Summary","The Monday operating brief","WEEKLY"],["Monthly Performance Review","Margin, volume and department trends","MONTHLY"],["Quarterly Business Review","Strategic performance narrative","QUARTERLY"],["Custom Template","Choose metrics and recipients","CUSTOM"]];
export default function Reporting(){
  const [template,setTemplate]=useState(0),[generating,setGenerating]=useState(false),[progress,setProgress]=useState(0),[preview,setPreview]=useState(false),[schedule,setSchedule]=useState(false),[notice,setNotice]=useState("");
  useEffect(()=>{if(!generating)return;const t=setInterval(()=>setProgress(p=>{if(p>=100){clearInterval(t);setGenerating(false);setPreview(true);return 100}return p+10}),220);return()=>clearInterval(t)},[generating]);
  function generate(){setProgress(0);setGenerating(true)}
  return <PrototypeShell eyebrow="JOURNEY 03 · AUTOMATED REPORTING" title="Monday report, ready Sunday night." description="Ghost Hand turns connected operating data into a concise executive narrative—automatically." actions={<button className="proto-btn dark" onClick={generate}>Generate weekly report →</button>}>
    <Toast message={notice}/>
    <section className="report-studio">
      <div className="report-paper"><div className="report-cover"><span>GHOST HAND INTELLIGENCE</span><small>PORSCHE CENTRE · WEEK 30</small><h2>Executive<br/>Operating Brief</h2><p>July 21–27, 2026</p><i>CONFIDENTIAL · SAMPLE DATA</i></div><div className="report-page"><span>01 · EXECUTIVE SUMMARY</span><h3>Margin strength is offsetting fixed-operations capacity risk.</h3><p>Monthly gross is pacing 18% above the six-month average. Three actionable anomalies represent $71.2K in near-term impact.</p><div className="report-kpis"><div><b>$472K</b><span>Gross profit</span></div><div><b>7</b><span>Signals</span></div><div><b>82%</b><span>Bay use</span></div></div><div className="report-line"/></div></div>
      <div className="report-controls"><div className="proto-panel-head"><div><span>GENERATION DEMO</span><h2>From exports to executive narrative</h2></div></div>{["Connect 12 exports","Analyze 14,802 records","Prioritize material changes","Format executive brief"].map((s,i)=><div className={`report-step ${progress>=(i+1)*20?"done":""}`} key={s}><i>{progress>=(i+1)*20?"✓":i+1}</i><span>{s}</span><b>{progress>=(i+1)*20?"COMPLETE":"QUEUED"}</b></div>)}{generating&&<div className="generation-progress"><i style={{width:`${progress}%`}}/><span>{progress}%</span></div>}<button className="proto-btn lime wide" onClick={generate} disabled={generating}>{generating?"Building your report…":"Generate weekly report"}</button><p>Estimated manual time: 4.5 hours · Ghost Hand: 2m 34s</p></div>
    </section>
    <section className="template-section"><div className="proto-panel-head"><div><span>REPORT LIBRARY</span><h2>Choose a narrative for the room.</h2></div></div><div className="template-grid">{templates.map((t,i)=><button className={template===i?"active":""} key={t[0]} onClick={()=>setTemplate(i)}><span>{t[2]}</span><div className="template-preview"><i/><i/><i/></div><b>{t[0]}</b><small>{t[1]}</small><em>{template===i?"SELECTED":"USE TEMPLATE →"}</em></button>)}</div></section>
    <section className="schedule-strip"><div><span>RECURRING DELIVERY</span><h2>On Ken’s desk before 7:00 AM.</h2><p>Email, Slack, or a secure report link—on the cadence the team already works.</p></div><button className="proto-btn dark" onClick={()=>setSchedule(true)}>Schedule delivery →</button></section>
    <Modal open={preview} onClose={()=>setPreview(false)} label="Generated report"><div className="modal-kicker">REPORT READY · 2M 34S</div><h2>Your weekly executive summary is ready.</h2><p>12 exports analyzed · 7 anomalies prioritized · 3 actions recommended</p><div className="modal-mini-grid"><div><span>GROSS PROFIT</span><b>$472K</b></div><div><span>AT-RISK VALUE</span><b>$71.2K</b></div><div><span>TIME RETURNED</span><b>4.5h</b></div></div><div className="modal-buttons"><button className="proto-btn ghost" onClick={()=>setSchedule(true)}>Schedule recurring</button><button className="proto-btn lime" onClick={()=>{downloadText("ghost-hand-weekly-report.txt","GHOST HAND INTELLIGENCE\nWeekly Executive Operating Brief\nGross profit: $472,350\nActive anomalies: 7\nRevenue impact: $284,000");setNotice("Report downloaded.")}}>Download report ↓</button></div></Modal>
    <Drawer open={schedule} onClose={()=>setSchedule(false)} label="Schedule report"><div className="modal-kicker">RECURRING DELIVERY</div><h2>Schedule the Monday brief.</h2><label className="field">RECIPIENTS<input defaultValue="ken@porschecentre.com"/></label><label className="field">CHANNEL<select><option>Email + secure link</option><option>Slack #leadership</option></select></label><label className="field">FREQUENCY<select><option>Every Monday</option><option>First business day monthly</option></select></label><div className="field-row"><label className="field">TIME<input type="time" defaultValue="07:00"/></label><label className="field">TIMEZONE<select><option>Pacific</option><option>Eastern</option></select></label></div><label className="toggle-line"><input type="checkbox" defaultChecked/>Send preview to me first</label><button className="proto-btn lime" onClick={()=>{setSchedule(false);setPreview(false);setNotice("Monday brief scheduled for 7:00 AM.")}}>Save schedule →</button></Drawer>
  </PrototypeShell>
}
