"use client";

import { useEffect, useState } from "react";
import { PrototypeShell } from "@/components/PrototypeShell";
import { Modal, Toast } from "@/components/PrototypeUI";
import { providers } from "@/lib/mock-data";

const defaults={vehicleSales:true,testDrives:true,leads:false,inventory:true,appointments:true,repairs:true,warranty:true,orders:true,partsInventory:true,backorders:true,email:true,slack:false,sms:false};
export default function Settings(){
  const [prefs,setPrefs]=useState(defaults),[connect,setConnect]=useState(false),[testing,setTesting]=useState(""),[notice,setNotice]=useState("");
  useEffect(()=>{const saved=localStorage.getItem("gh-prefs");if(saved)setPrefs(JSON.parse(saved))},[]);
  function toggle(key:keyof typeof defaults){const next={...prefs,[key]:!prefs[key]};setPrefs(next);localStorage.setItem("gh-prefs",JSON.stringify(next))}
  function test(name:string){setTesting(name);setTimeout(()=>{setTesting("");setNotice(`${name} connection verified.`);setTimeout(()=>setNotice(""),2200)},900)}
  return <PrototypeShell eyebrow="WORKSPACE CONFIGURATION" title="Settings & connections." description="Show how Ghost Hand fits the systems and operating rhythm the dealership already uses." actions={<><button className="proto-btn ghost" onClick={()=>{localStorage.removeItem("gh-prefs");localStorage.removeItem("gh-resolved");localStorage.removeItem("gh-role");setPrefs(defaults);setNotice("Demo state reset.")}}>Reset demo</button><button className="proto-btn dark" onClick={()=>setConnect(true)}>Add connection +</button></>}>
    <Toast message={notice}/>
    <section className="settings-section"><div className="settings-title"><span>01</span><div><h2>Connected systems</h2><p>No rip-and-replace. Connect the tools already running the dealership.</p></div></div><div className="provider-grid">{providers.map(p=><article key={p.name}><div className="provider-logo">{p.name.slice(0,2)}</div><div><b>{p.name}</b><span>{p.detail}</span><small>{p.last}</small></div><i className={p.status.toLowerCase()}>{p.status}</i><button onClick={()=>test(p.name)}>{testing===p.name?"Testing…":p.status==="Connected"?"Test":"Configure"} →</button></article>)}</div></section>
    <section className="settings-section"><div className="settings-title"><span>02</span><div><h2>Data sources</h2><p>Choose what enters the intelligence layer. Changes save automatically in this demo.</p></div></div><div className="source-columns">{[["Sales",["vehicleSales","Vehicle sales"],["testDrives","Test drives"],["leads","Leads"],["inventory","Inventory"]],["Service",["appointments","Appointments"],["repairs","Repair orders"],["warranty","Warranty claims"]],["Parts",["orders","Orders"],["partsInventory","Inventory"],["backorders","Backorders"]]].map(group=><article key={group[0] as string}><h3>{group[0]}</h3>{group.slice(1).map(item=>{const pair=item as string[];const key=pair[0] as keyof typeof defaults;return <label key={key}><span>{pair[1]}</span><input type="checkbox" checked={prefs[key]} onChange={()=>toggle(key)}/><i/></label>})}</article>)}</div></section>
    <section className="settings-section"><div className="settings-title"><span>03</span><div><h2>Alert preferences</h2><p>Route material signals to the right people without creating more noise.</p></div></div><div className="preference-panel">{[["email","Email intelligence","Real-time for critical · Daily digest otherwise"],["slack","Slack integration","#leadership-ops"],["sms","SMS escalation","Critical impact above $25K"]].map(([key,title,desc])=><label key={key}><div><b>{title}</b><span>{desc}</span></div><input type="checkbox" checked={prefs[key as keyof typeof defaults]} onChange={()=>toggle(key as keyof typeof defaults)}/><i/></label>)}<button onClick={()=>test("Notification")} className="proto-btn ghost">{testing==="Notification"?"Sending test…":"Send test notification"}</button></div></section>
    <section className="settings-section"><div className="settings-title"><span>04</span><div><h2>Team access</h2><p>Switch roles from any page to demonstrate the perspective each leader receives.</p></div></div><div className="team-table">{[["Ken Walters","Dealer Principal","ken@porschecentre.com","Now"],["Maya Chen","General Manager","maya@porschecentre.com","12 min"],["Carlos M.","Service Manager","carlos@porschecentre.com","1 hr"],["Sarah L.","Sales Advisor","sarah@porschecentre.com","Yesterday"]].map(u=><div key={u[1]}><i>{u[0].split(" ").map(x=>x[0]).join("")}</i><b>{u[0]}<small>{u[2]}</small></b><span>{u[1]}</span><em>{u[3]}</em><button>•••</button></div>)}<button className="proto-text-btn" onClick={()=>setNotice("Invitation workflow opened in demo mode.")}>+ Invite team member</button></div></section>
    <Modal open={connect} onClose={()=>setConnect(false)} label="Add DMS connection"><div className="modal-kicker">MOCK CONNECTION FLOW</div><h2>Add a DMS connection.</h2><p>No credentials are transmitted in this prototype.</p><label className="field">PROVIDER<select><option>CROSS3</option><option>CDK Global</option><option>Reynolds & Reynolds</option><option>Porsche PIWIS</option></select></label><label className="field">DEALER ID<input placeholder="PC-10294"/></label><label className="field">API CREDENTIAL<input type="password" defaultValue="prototype-key"/></label><button className="proto-btn lime" onClick={()=>{setConnect(false);setNotice("Connection verified. 12 exports found.")}}>Test & connect →</button></Modal>
  </PrototypeShell>
}
